Add dashboard endpoints
cyklop123/callories-callculator-api pull request #4
Opened 2021-05-28 15:04 UTC by kar118

2021-05-28 15:07 UTC, cyklop123 commented on routes/dashboard.js
> -dashboard.get('/', isAdmin, (req, res) => {
ten get jest nie potrzebny, ustaliliśmy to

2021-05-28 15:09 UTC, cyklop123 commented on routes/dashboard.js
> +
Nie sprawdzasz czy produkt o takim id istnieje tylko od razu dodajesz.

2021-05-28 15:10 UTC, cyklop123 commented on routes/dashboard.js
> +            const product = (await Product.find({ _id: newProduct.product_id }))[0]
Mógłbyś wtedy tutaj wykorzystać pobrany wcześniej produkt (przy sprawdzaniu)

2021-05-28 15:12 UTC, kar118 commented on routes/dashboard.js
> -dashboard.get('/', isAdmin, (req, res) => {
to jest usunięte

2021-05-28 15:22 UTC, cyklop123 requested changes

2021-05-28 15:22 UTC, cyklop123 commented on routes/dashboard.js
> +        const userProduct = await UserProduct.findByIdAndRemove({ _id: req.params.id }, {__v:0}).exec()
Tak na przyszłość findByIdAndRemove usuwa obiekt i go zwraca. Jak nie potrzebujesz tego to zrób po prostu remove. Ale ja bym jednak był za tym żeby ten endpoint zwrócił usunięty rekord

2021-05-28 15:22 UTC, cyklop123 commented on routes/dashboard.js
> +        const product = (await Product.find({ _id: userProduct.product_id }))[0]
użyj po prostu findOne

2021-05-28 15:22 UTC, cyklop123 commented on routes/dashboard.js
> +        res.json({
Po co to przepisujesz ? Użyj projekcji w find

2021-05-28 15:22 UTC, cyklop123 commented on routes/dashboard.js
> +                _id: newProduct.id,
nie przeliczyłeś kcal,carbs,prots,fats

2021-05-28 15:22 UTC, cyklop123 commented on routes/dashboard.js
> +            product: {
znowu nie przeliczyłeś kcal,carbs,prots,fats

2021-05-28 15:25 UTC, cyklop123 commented on routes/dashboard.js
> -dashboard.get('/', isAdmin, (req, res) => {
ok xd

2021-05-28 15:27 UTC, cyklop123 commented on routes/dashboard.js
> +    const product = (await Product.find({ _id: newProduct.product_id }))[0]
Dałeś to poza try

2021-05-28 15:28 UTC, cyklop123 requested changes
.

2021-05-31 13:35 UTC, cyklop123 approved these changes

2021-05-31 13:41 UTC, cyklop123 approved these changes
Gitara

2021-05-31 13:41 UTC, merged